# .github/workflows/ci.yml
name: CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install deps
      run: npm ci
    - name: Run tests with coverage
      run: npm run coverage
    - name: Set version env
      id: vars
      run: |
        PKG_VERSION=$(node -p "require('./package.json').version")
        echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_OUTPUT

docker:
  needs: build-test
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v3
  - name: Set up Buildx
    uses: docker/setup-buildx-action@v3
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - name: Extract metadata (tags, labels)
    id: meta
    uses: docker/metadata-action@v5
    with:
      images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=sha,format=short
        type=raw,value=v${{ needs.build-test.outputs.PKG_VERSION }}
      labels: |
        org.opencontainers.image.title=tp-cicd-dockerhub
  - name: Build and push
    uses: docker/build-push-action@v6
    with:
      context: .
      file: ./Dockerfile
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.IMAGE_NAME }}:buildcache
      cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:buildcache,mode=max
